name: Build Wessam Pro Dylib

# متى يشتغل السيرفر؟ عند رفع أي تعديل أو تشغيله يدوياً
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # نستخدم سيرفرات ماك لضمان التوافق مع iOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (ldid & dpkg)
        run: |
          brew install ldid
          brew install dpkg

      - name: Setup Theos (بيئة البناء)
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup iOS SDKs (مكاتب أبل)
        run: |
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip -q master.zip
          cp -R sdks-master/* ~/theos/sdks/
          rm -rf master.zip sdks-master
          

      - name: Build Tweak (عملية الصهر)
        run: |
          make clean
          make FINALPACKAGE=1

      - name: Upload Dylib Artifact (رفع السبيكة الجاهزة)
        uses: actions/upload-artifact@v4
        with:
          name: WessamMod-Dylib-Ready
          # هنا السيرفر راح يبحث عن ملف الدايلب ويسحبه لك عشان تحمله
          path: .theos/obj/**/*.dylib 
          
